trainer:
  max_epochs: 30
  accelerator: gpu
  devices: 1
  num_nodes: 1
  strategy: ddp_find_unused_parameters_true
  precision: bf16-mixed
  gradient_clip_val: 5.0
  gradient_clip_algorithm: norm
  accumulate_grad_batches: 1
  # callbacks:
  # - class_path: lightning.pytorch.callbacks.ModelCheckpoint
  #   init_args:
  #     dirpath: checkpoints/physics
  #     filename: "Physics-{epoch:03d}-{val/loss:.4f}"
  #     monitor: val/loss  # Monitor total loss now
  #     mode: min
  #     save_top_k: 1
  #     save_last: true
  #     auto_insert_metric_name: false
  #     every_n_epochs: 1
  #     save_on_train_epoch_end: true
  # logger:
  #   class_path: lightning.pytorch.loggers.WandbLogger
  #   init_args:
  #     project: "JEPA"
  #     name: "PointMaze/physics"
  #     log_model: true

model:
  lr: 5e-3
  final_lr: 1e-5
  warmup_steps: 500
  hidden_dim: 32
  patch_size: 8
  num_heads: 4
  num_layers: 3

# ============================================================================
# Data (unchanged)
# ============================================================================
data:
  data_path: data/train_trajectories_1000_100_4_64_largerdot.npz
  batch_size: 256
  num_workers: 2
  pin_memory: true
  val_size: 0.1
  normalize: false